import type { Room, Booking } from '@/types';
import { generateId, todayStr } from './date';
import { addDays, format } from 'date-fns';

export function getInitialRooms(): Room[] {
  const now = new Date().toISOString();
  return [
    {
      id: generateId(),
      roomNumber: '101',
      name: '听雨阁',
      type: 'standard',
      price: 288,
      bedType: 'double',
      capacity: 2,
      facilities: ['WiFi', '空调', '电视', '独立卫浴', '24小时热水', '吹风机'],
      description: '温馨舒适的标准间，配备一张双人床，适合情侣或闺蜜出行。',
      status: 'active',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomNumber: '102',
      name: '观云轩',
      type: 'standard',
      price: 288,
      bedType: 'twin',
      capacity: 2,
      facilities: ['WiFi', '空调', '电视', '独立卫浴', '24小时热水', '吹风机', '阳台'],
      description: '带独立阳台的标准间，两张单人床，适合朋友同住。',
      status: 'active',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomNumber: '201',
      name: '揽月楼',
      type: 'deluxe',
      price: 488,
      bedType: 'king',
      capacity: 2,
      facilities: ['WiFi', '空调', '电视', '独立卫浴', '24小时热水', '吹风机', '洗漱用品', '迷你吧', '山景', '保险箱'],
      description: '豪华大床房，全景落地窗，可欣赏远山美景。',
      status: 'active',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomNumber: '202',
      name: '望海居',
      type: 'deluxe',
      price: 528,
      bedType: 'king',
      capacity: 2,
      facilities: ['WiFi', '空调', '电视', '独立卫浴', '24小时热水', '吹风机', '洗漱用品', '迷你吧', '海景', '阳台', '咖啡机'],
      description: '豪华海景房，面朝大海，春暖花开。配备独立阳台和咖啡机。',
      status: 'active',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomNumber: '301',
      name: '竹韵套房',
      type: 'suite',
      price: 888,
      bedType: 'king',
      capacity: 2,
      facilities: ['WiFi', '空调', '电视', '独立卫浴', '24小时热水', '吹风机', '洗漱用品', '迷你吧', '山景', '阳台', '保险箱', '咖啡机', '冰箱', '拖鞋'],
      description: '顶级套房，独立起居室和卧室，配备大浴缸，尊享品质体验。',
      status: 'active',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomNumber: '302',
      name: '阖家欢',
      type: 'family',
      price: 688,
      bedType: 'double',
      capacity: 4,
      facilities: ['WiFi', '空调', '电视', '独立卫浴', '24小时热水', '吹风机', '洗漱用品', '迷你吧', '冰箱', '拖鞋'],
      description: '温馨家庭房，一张双人床+两张单人床，适合全家出行。',
      status: 'active',
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function getInitialBookings(rooms: Room[]): Booking[] {
  if (rooms.length === 0) return [];
  const now = new Date().toISOString();
  const today = new Date();

  const bookings: Booking[] = [
    {
      id: generateId(),
      roomId: rooms[0].id,
      guestName: '张先生',
      guestPhone: '13800138001',
      guestIdCard: '110101199001011234',
      checkIn: format(addDays(today, -2), 'yyyy-MM-dd'),
      checkOut: format(addDays(today, 1), 'yyyy-MM-dd'),
      guests: 2,
      totalPrice: 288 * 3,
      status: 'checked-in',
      notes: '需要安静的房间',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomId: rooms[1].id,
      guestName: '李女士',
      guestPhone: '13900139002',
      guestIdCard: '110101199203045678',
      checkIn: todayStr(),
      checkOut: format(addDays(today, 2), 'yyyy-MM-dd'),
      guests: 2,
      totalPrice: 288 * 2,
      status: 'confirmed',
      notes: '下午3点左右到店',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomId: rooms[2].id,
      guestName: '王总',
      guestPhone: '13700137003',
      guestIdCard: '310101198505069012',
      checkIn: format(addDays(today, 3), 'yyyy-MM-dd'),
      checkOut: format(addDays(today, 5), 'yyyy-MM-dd'),
      guests: 2,
      totalPrice: 488 * 2,
      status: 'confirmed',
      notes: '商务出行，需要发票',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomId: rooms[3].id,
      guestName: '陈小姐',
      guestPhone: '13600136004',
      checkIn: format(addDays(today, 1), 'yyyy-MM-dd'),
      checkOut: format(addDays(today, 4), 'yyyy-MM-dd'),
      guests: 2,
      totalPrice: 528 * 3,
      status: 'confirmed',
      notes: '蜜月旅行，希望房间有浪漫布置',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomId: rooms[5].id,
      guestName: '赵先生一家',
      guestPhone: '13500135005',
      checkIn: format(addDays(today, 7), 'yyyy-MM-dd'),
      checkOut: format(addDays(today, 10), 'yyyy-MM-dd'),
      guests: 4,
      totalPrice: 688 * 3,
      status: 'confirmed',
      notes: '两大两小，需要儿童用品',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      roomId: rooms[4].id,
      guestName: '孙先生',
      guestPhone: '13400134006',
      checkIn: format(addDays(today, -5), 'yyyy-MM-dd'),
      checkOut: format(addDays(today, -2), 'yyyy-MM-dd'),
      guests: 2,
      totalPrice: 888 * 3,
      status: 'checked-out',
      notes: '',
      createdAt: now,
      updatedAt: now,
    },
  ];

  return bookings;
}
